version: '3.4'
services:
  api:
    image: avenus/webapi
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
    - "14331:1433"